### ISSUE TITLE
Create REST endopoints to retrieve Public Transport schedules 

### ISSUE THREAD

**Issue by isalvadori** [de-jena/broker#10]
We would need a REST API to query for some static public transport data, as well as for some real time updates coming from the public transports. This issue deals mainly with the first case. In particular, as required by INAVET, they would need some endpoints to:
1. Query Public Transport (PT) schedules by day
2. Query PT schedules by day and line numbers
3. Query PT schedules by day and time
4. Query PT schedules by day and stop DHIDs 
5. Query PT schedules by day and stop names

The returned object should contain: 
- The Vehicle-Id (vehicle-number)
- The line-number
- The route-number
- The course-number
- The starting stop-post with the scheduled departure time
- The stop-posts on the mission with the scheduled arrival and departure time
- The end stop-post with the scheduled arrival time
- The stop-posts should contain a unique identifier (e. g. the DHID-Code, EPON-Code, etc.) and ideally a 3D-geo-position
- The stop-post should contain the prognosis for the dwell time
- The stop-post should contain an attribute, whether it is a planned stop or a request stop.
- The stop-post should contain an attribute, whether it is a transit stop.
- If possible, we also need the data for the approach run of the vehicle to the starting stop-post (e. g. the vehicle comes from depot).

**Comment by juergen-albert** [comment]
LGTM
